name: Approval Request

on:
  push:
    paths:
      - '.github/sql_uploads/**'

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
    - name: Request Approval
      uses: actions/github-script@v6
      with:
        script: |
          const { exec } = require("child_process");
          const fs = require("fs");

          const files = fs.readdirSync(".github/sql_uploads");
          if (files.length === 0) {
            console.log("No SQL files to process.");
            return;
          }

          const filePath = `.github/sql_uploads/${files[0]}`; // Process the first file
          const approvalUrl = `https://github.com/${process.env.GITHUB_REPOSITORY}/actions/new/execute_sql_uploads?file_path=${filePath}`;
          const approvalMessage = `A new SQL file has been uploaded. Please approve the execution by visiting [this link](${approvalUrl}).`;

          const options = {
            method: 'POST',
            headers: {
              'Authorization': `token ${process.env.GITHUB_TOKEN}`,
              'Accept': 'application/vnd.github.v3+json',
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({
              "body": approvalMessage,
              "title": "SQL Execution Approval Request"
            })
          };

          fetch(`https://api.github.com/repos/${process.env.GITHUB_REPOSITORY}/issues`, options)
            .then(response => response.json())
            .then(data => console.log("Approval request created:", data))
            .catch(error => console.error("Error creating approval request:", error));
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
