name: Table validations

on:
  pull_request:
  branches:
    - main
    paths:
      - '.github/sql_scripts/**'
jobs:
    validate-sql-script:
        runs-on:ubuntu-latest
    permissions:
        pull-requests: write
        contents: read
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      -name: Setting up my Python environment
       uses: actions/setup-python@v3
        with:
            python-version: '3.9'

      -name: Install dependencies
       run: |
            python -m pip install --upgrade pip
            pip install snowflake-connector-python
            pip install PyGithub

      -name: Getting my changed files in a particular Pull Request
        id: changed-files
        run: |
        files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^.github/sql_scripts/' || true)
          echo "files=$files" >> $GITHUB_OUTPUT

      - name: Validate SQL Objects
        if: steps.changed-files.outputs.files != ''
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in ${{ steps.changed-files.outputs.files }}; do
            echo "Validating $file"
            
            output=$(python .github/scripts/validate_snowflake_scripts.py "$file")
            exit_code=$?
            
            # Prepare comment body
            comment="SQL Validation Results for \`$file\`\n\n$output"
            
            if [ $exit_code -ne 0 ]; then
              comment="$comment\n\n Warning: Please ensure all objects exist in Snowflake DEV before merging."
            else
              comment="$comment\n\n All queries validated successfully!"
            fi
            
            # Post comment using GitHub CLI
            gh pr comment ${{ github.event.number }} --body "$comment"
            
            if [ $exit_code -ne 0 ]; then
              echo "Validation failed for $file"
              exit 1
            fi
          done
