name: Check SQL Scripts

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/sql_scripts/**'

jobs:
  check-sql:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install snowflake-connector-python

    - name: Get Changed Files
      id: changes
      run: |
        echo "::set-output name=files::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '.sql$' | tr '\n' ' ')"
    
    - name: Run SQL Checker
      run: |
        python .github/scripts/validate_snowflake_scripts.py "${{ steps.changes.outputs.files }}"
