name: SQL Validation Workflow

on:
  push:
    paths:
      - '.github/sql_scripts/**'

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Required to get file changes

      - name: Get changed files
        id: changed-files
        run: |
          echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD | grep '^.github/sql_scripts/.*\.sql$' | tr '\n' ' ')"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python
      
      - name: Run SQL validation
        run: python .github/scripts/validate.py ${{ steps.changed-files.outputs.files }}
